// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    // If you set another name in wrangler.toml as the value for 'binding',
    // replace "AI" with the variable name you defined.
    AI: any;
}
